baseURL = 'https://rendaniwrites-portfolio.netlify.app/'
languageCode = 'en-us'
title = 'Rendani Luvhengo'

[params]
  firstName = "Rendani"
  brand = "Rendani Luvhengo"
  description = "Welcome to my personal website."
  email = "rluvhengo2@gmail.com"
  linkedin = "https://www.linkedin.com/in/rendani-luvhengo/"
  github = "https://github.com/Renda02"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "work"
    name = "Resume"
    url = "/work/"
    weight = 2
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    identifier = "api"
    name = "API sample"
    url = "/api/"
    weight = 4
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 5

[[redirects]]
from = '/about/'
to = '/'
status = 301
